### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by philipperemy** [tyiannak/pyAudioAnalysis#75]
Hey guys,
Is there a schedule for python3 compatibility?
Thanks

**Comment by keryil** [comment]
I would also like to find out if there are any plans. Currently I am working on a Python 3 port anyway, but since there is a lot of unpickling involved, I am not sure how much I will be able to cover for now. sklearn is already warning me about the perils of unpickling pre-0.18 SVMs and such.

**Comment by philipperemy** [comment]
@keryil yes it's not very straight forward. That's why I opened a ticket there!

Let me know if you can complete it. If so, please open a Pull Request!

**Comment by hydra324** [comment]
@philipperemy If you want to use this library with python 3, you just have to convert the source. Use '2to3.py' script given in the "tools" directory.

**Comment by gannebamm** [comment]
@hydra324 at least for me it is not that easy.

**Comment by hydra324** [comment]
@gannebamm did you test this library? How was the performance?

**Comment by dmoham1476** [comment]
2to3 didnt do a good job

**Comment by eduamf** [comment]
Why  "2to3 didnt do a good job"?

**Comment by philipperemy** [comment]
@eduamf because it's not as simple as running a 2to3 script.

Google has millions of legacy code in python2 and probably will never migrate it to python3 because it requires a huge work.

2to3 works well when it comes to replace `print "hello"` by `print("hello")` but on many more complex tasks, it's very difficult to have it working

**Comment by naktinis** [comment]
I've migrated enough code so that I'm able to run SVM classification on Python 3 (in my [fork](https://github.com/naktinis/pyAudioAnalysis)).

I can't guarantee that everything else will work, but feel free to file a pull request. I've also added `setup.py` to make it possible to install using `pip install git+https://github.com/naktinis/pyAudioAnalysis.git`.

I hope that @tyiannak will some day have time to do something similar in the original repository.

**Comment by kmouts** [comment]
In  the [README.md](https://github.com/tyiannak/pyAudioAnalysis) file, a note should be added regarding the Python Version needed by the library. 

I've also managed to port it to Python 3.6.3, but it took some effort.

A problem exists with libmagic used by eye package in Windows 64 bit. Solved it after looking [here](https://stackoverflow.com/questions/44483519/problems-importing-magic-on-windows-64-bit),
and making changes in the magic.py file, regarding the constructor of the class to use the specific magic.mgc file... 

I used [winPython ](https://sourceforge.net/projects/winpython/)64bit on Windows 10 64bit (WinPython-64bit-3.6.3.0Qt5).

**Comment by RefiPeretz** [comment]
Do you know this guy?  https://github.com/ksingla025/pyAudioAnalysis3 is he part of the developers do you recommend this repository?

**Comment by philipperemy** [comment]
@naktinis thank you very much

**Comment by philipperemy** [comment]
@ksingla025 hey! How confident are you with your python3 implementation? Thanks

**Comment by philipperemy** [comment]
@RefiPeretz I've contacted the guy. Let's wait for his response (if any).

**Comment by tsando** [comment]
hi! does anyone know which version of python is this code compatible with? Clearly not python 3+ but which version of python 2 is this for? Thanks.

**Comment by philipperemy** [comment]
@tsando worked well with 2.7 as far as I remember

**Comment by andreaschandra** [comment]
@tsando i use 2.7

**Comment by srigsby** [comment]
would be nice to include the version that it was built for/does run on (2.7 from comments above) included somewhere in the readme and/or at least the wiki.

**Comment by ksingla025** [comment]
Hi, sorry never saw these messages. the one I shared works perfectly and is just forked from original. converted using 2to3 and then some minor syntax fixes. It works perfectly, have been using it in my work.

**Comment by toddrjen** [comment]
The README says that it is supposed to support Python3, but the unit tests still fail on Python3.  It seems there are a bunch of places where `print` is used as a statement rather than a function (namely `audioAnalysisRecordAlsa.py`, `analyzeMovieSound.py`, `data/testComputational.py`, `audacityAnnotation2WAVs.py`, and `data/recordRadio.py`).  Using `from __future__ import print_function` can make print work the same in Python 2 as it does in Python2.  There may be other issues as well.

**Comment by ncrmro** [comment]
Just an update on this trainClassifier fails on 3.8. [The function time.clock() has been removed](https://stackoverflow.com/a/58569410/4289267)

```
AttributeError: module 'time' has no attribute 'clock'
```
