### ISSUE TITLE
eyeD3 version 

### ISSUE THREAD

**Issue by bninopaul** [tyiannak/pyAudioAnalysis#2]
this project is amazing! I have tried the speaker diarization feature and it really works! Super Cool! However it is also worthwhile to specify the version of eyeD3 being used.. While I was installing this package,  there was an error on eyeD3 module being used. The package will not work with the latest eyeD3 of versions 0.7.x but with versions 0.6.x. 

Hope this project will be added in PyPi. The project is promising!

**Comment by clazito** [comment]
How do I install the old 0.6.x version instead of 0.7.x?

**Comment by willpearse** [comment]
Go back through the commits, find the version you want to load, and then clone that. Does that make sense?

**Comment by tyiannak** [comment]
An update: please use the latest library version, and install eyed3 using pip (see wiki and README for instructions).

**Comment by dofine** [comment]
```
Traceback (most recent call last):
  File "pyAudioAnalysis/audioAnalysis.py", line 426, in <module>
    dirMp3toWavWrapper(args.input, args.rate, args.channels)
  File "pyAudioAnalysis/audioAnalysis.py", line 30, in dirMp3toWavWrapper
    audioBasicIO.convertDirMP3ToWav(directory, samplerate, channels, useMp3TagsAsNames)
  File "/Users/dofine/Devel/audioAna/pyAudioAnalysis/audioBasicIO.py", line 17, in convertDirMP3ToWav
    tag = eyed3.Tag()
AttributeError: 'module' object has no attribute 'Tag'
```
eyed3 API change?

**Comment by The-Gupta** [comment]
I randomly installed eyed3==0.7.11 (pip install eyed3==0.7.11) and it works just fine for me.
